
# Keep uv-lock up-to-date after pre-commit changes.
repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.13
    hooks:
      - id: uv-lock

  # Auto-export uv.lock to requirements.txt
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.13
    hooks:
      - id: uv-export

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff # linter
        args: [--fix]
      - id: ruff-format # formatter

  # - repo: https://github.com/psf/black-pre-commit-mirror
  #   rev: 24.8.0
  #   hooks:
  #     - id: black-jupyter
  #       # It is recommended to specify the latest version of Python
  #       # supported by your project here, or alternatively use
  #       # pre-commit's default_language_version, see
  #       # https://pre-commit.com/#top_level-default_language_version
  #       language_version: python3.8

  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)