# Sample parameters to customize a single subscriber's issue

email: SUBSCRIBER_NAME@SERVER.COM
admin: True # Append technical logs (such as exceptions) at the end of the issue email? Deleting this line also sets the value to False.
nba_teams:  # Track any NBA teams? If none, delete or comment out this section.
    - Knicks

# Configure the forecast
# To get the values to put below...
# 1. Find the latitude and longitude for your town using Google Maps for example
# 2. Run the following code with that lat and lon:
#   url =f"https://api.weather.gov/points/{lat},{lon}"
#   r = requests.get(url)
#   r.json()
# 3. Extract the following from `r`:  'gridId' (-> office), 'gridX', 'gridY'
# 4. Entre the town name in your own words
nws:
  office: 3-LETTER-CODE
  grid_x: INTEGER
  grid_y: INTEGER
  location_name: STRING

# Customize content
editorial:
  add_shared_thoughts: False # If True, in addition to list of thoughts_of_the_day below, the issue will also sample the "Thought of the Day" quotes from the shared `thoughts_of_the_day.yml` file.
  last_headlines_file: last_headlines_SUBSCRIBER_NAME.txt # The name of the file on S3 to cache headlines from the last issue. Used to ensure that Finite News doesn't report any headlines the user already saw in the last issue.
sources:
  events_sources:  # Optional
    - name of event source to include
  events_frequency: # How often to include it in issues?
    frequency: every_other_week # weekly or every_other_week (odd week number)
    day_of_week: Monday # Full day name, case insensitive

# The newspaper slogan that goes under the logo in each issue.
# One slogan from the list is selected at random each day.
# Edit or expand the list as you like.
slogans:
  - 1/100th the News That’s Fit to Print.

# A list of quotes or jokes. The section "Thought of Day: will sample one each day.
# See also the parameter above `add_shared_thoughts`.
# Edit or expand the list as you like.
thoughts_of_the_day:
  - "When I was a boy and I would see scary things in the news, my mother would say to me, 'Look for the helpers. You will always find people who are helping.' - Mr Rogers"